# Generated by Django 4.0.3 on 2022-03-19 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route_permit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'vehicle owner', 'verbose_name_plural': 'Owner Information'},
        ),
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('vehicle_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('model_number', models.CharField(max_length=30)),
                ('chasis_number', models.CharField(max_length=30)),
                ('engine_number', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='route_permit.owner')),
            ],
        ),
    ]
